import java.io.*;
class Math_lib
{
	static double a;
	public static void main(String[] args)throws Exception
	{
		a=Math.min(234,234);
		System.out.println("min(234,234);: "+a);
		a=Math.max(24.5554,24.5555);
		System.out.println("max(24.5554,24.5555)"+a);
		a=Math.cbrt(-3243434);
		System.out.println("cbrt(-3243434)"+a);
		a=Math.sqrt(11111112);
		System.out.println("sqrt(11111112)"+a);
		a=Math.sqrt(-11111112);
		System.out.println("sqrt(-11111112)"+a);
		a=Math.log(100000);
		System.out.println("log(-100000)"+a);
		a=Math.log(100000);
		System.out.println("log(100000)"+a);
		a=Math.abs(-11111);
		System.out.println("abs-11111 : "+a);
		a=Math.round(8.5);
		System.out.println("round 8.5 : "+a);
		a=Math.round(-8.5);
		System.out.println("round -8.5 : "+a);
		a=Math.round(-8.4);
		System.out.println("round -8.4 : "+a);
		a=Math.round(-8.54);
		System.out.println("round -8.54 : "+a);
		a=Math.rint(8.4);
		System.out.println("Math.rint(8.4) : "+a);
		a=Math.rint(8.45);
		System.out.println("Math.rint(8.45) : "+a);
		a=Math.rint(8.5);
		System.out.println("Math.rint(8.5) : "+a);
		a=Math.rint(8.51);
		System.out.println("Math.rint(8.51) : "+a);
		a=Math.rint(8.6);
		System.out.println("Math.rint(8.6) : "+a);
		a=Math.rint(-8.4);
		System.out.println("Math.rint(-8.4) : "+a);
		a=Math.rint(-8.5);
		System.out.println("Math.rint(-8.5) : "+a);
		a=Math.rint(-8.51);
		System.out.println("Math.rint(-8.51) : "+a);
		a=Math.rint(-8.6);
		System.out.println("Math.rint(-8.6) : "+a);
		a=Math.ceil(8.4);
		System.out.println("Math.ceil(8.4) : "+a);
		a=Math.ceil(8.5);
		System.out.println("Math.ceil(8.5) : "+a);
		a=Math.ceil(8.51);
		System.out.println("Math.ceil(8.51) : "+a);
		a=Math.ceil(-8.4);
		System.out.println("Math.ceil(-8.4) : "+a);
		a=Math.ceil(-8.5);
		System.out.println("Math.ceil(-8.5) : "+a);
		a=Math.ceil(-8.51);
		System.out.println("Math.ceil(-8.51) : "+a);
		a=Math.floor(8.4);
		System.out.println("Math.floor(8.4) : "+a);
		a=Math.floor(8.5);
		System.out.println("Math.floor(8.5) : "+a);
		a=Math.floor(8.51);
		System.out.println("Math.floor(8.51) : "+a);
		a=Math.floor(-8.4);
		System.out.println("Math.floor(-8.4) : "+a);
		a=Math.floor(-8.5);
		System.out.println("Math.floor(-8.5) : "+a);
		a=Math.floor(-8.51);
		System.out.println("Math.floor(-8.51) : "+a);
		a=Math.exp(1);
		System.out.println("Math.exp(1) : "+a);
		a=Math.exp(-12);
		System.out.println("Math.exp(-12) : "+a);
		a=Math.cos(1/90);
		System.out.println("Math.cos(1/90)==sec90 : "+a);
	}
}